# Generated by Django 3.2.11 on 2022-01-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic_crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.CharField(choices=[('ADMIN', 'Admin team, managing users and accessing all data'), ('SALES', 'Sales team, managing clients and contracts'), ('SUPPORT', 'Suppport team, managing events')], default='SALES', max_length=7),
            preserve_default=False,
        ),
    ]
