# Generated by Django 3.2.11 on 2022-01-26 11:24

from django.db import migrations

def create_groups(apps, schema_migration):

    User = apps.get_model('epic_crm', 'User')
    Group = apps.get_model('auth', 'Group')

    sales = Group(name='sales')
    sales.save()

    support = Group(name='support')
    support.save()


class Migration(migrations.Migration):

    dependencies = [
        ('epic_crm', '0002_user_team'),
    ]

    operations = [
        migrations.RunPython(create_groups)
    ]
