# Generated by Django 3.2.11 on 2022-02-08 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epic_crm', '0005_auto_20220202_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='epic_crm.client'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('incoming', 'Future event'), ('over', 'Past event')], default='incoming', max_length=20),
        )
    ]
