# Generated by Django 3.2.11 on 2022-02-08 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epic_crm', '0006_auto_20220208_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='team',
        ),
    ]
