# Generated by Django 3.2.11 on 2022-02-08 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic_crm', '0008_auto_20220208_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
