# Generated by Django 3.2.11 on 2022-02-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic_crm', '0009_alter_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='is_signed',
            field=models.BooleanField(default=False),
        ),
    ]
